name: Create Next.js App and Commit (Manual)

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'info'
        type: choice
        options:
          - info
          - warning
          - debug
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x' # Or your preferred Node.js version

      - name: Create Next.js app
        run: npx create-next-app@latest wbdcps

      - name: Commit changes
        run: |
          cd wbdcps
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Create Next.js app"
          git push origin HEAD:main
