name: Setup next + libp2p

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
        type: choice
        options:
          - info
          - warning
          - debug

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Create Next.js app
        run: npx create-next-app@latest wbrtc

      - name: Install libp2p
        run: npm install npm install libp2p @libp2p/gossipsub @libp2p/websockets @libp2p/websockets @libp2p/tcp @libp2p/mplex @libp2p/noise it-length-prefixed it-pushable it-pipe it-ws @libp2p/bootstrap

      - name: Transfer Contents to Root
        run: |
          cd wbrtc
          shopt -s dotglob
          mv * ..
          cd ..
          rm -rf wbrtc

      - name: Commit changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Transfer Next.js app contents to root"
          git push origin HEAD:main
